data1 = {
    'catholic_devotional_the_tradition': 'Yes',
    'trust_the_bible_series': 'Yes',
    'know_the_bible_series': 'Yes',
    'mysteries_of_the_messiah': 'Yes',
    'how_to_live_the_bible': 'Yes',
    'worship_and_word': 'Yes',
    'bible_gateway_news': 'Yes',
    'visual_verse_of_the_day_niv': 'Yes',
    'visual_verse_of_the_day_kjv': 'Yes',
    'visual_verse_of_the_day_nasb': 'Yes',
    'Verse of the Day Digest': 'Yes',
    'votd1': 'VOICE',
    'votd2': 'NLT',
    'votd3': 'HCSB',
    'votd4': 'ESV',
    'votd5': 'NIV',
    'visual_verse_of_the_day_rvr': 'Yes',
    '40 Day Journey with Dietrich Bonhoeffer': 'Yes',
    'cs_lewis_daily': 'Yes',
    'charles_spurgeons_morning_and_evening': 'Yes',
    'Standing Strong Through the Storm': 'Yes',
    'john_piper_devotional': 'Yes',
    'praying_the_scriptures_with_chuck_swindoll': 'Yes',
    'walk_closer_with_jesus': 'Yes',
    'investigating_faith_with_lee_strobel': 'Yes',
    'anchor_devotional': 'Yes',
    'daily_audio_bible': 'Yes',
    'revised_common_lectionary_reading_plan': 'Yes',
    'old_and_new_testament_niv_version_365_days': 'Yes',
    'old_and_new_testament_kjv_365_days': 'Yes',
    'new_testament_in_a_year_niv_365_days': 'Yes',
    'daniel_prayer': 'Yes',
    'dallas_willard_automation': 'Yes',
    'john_ortberg_devotionals': 'Yes',
    'codes_for_christian_living': 'Yes',
    'faith_and_work': 'Yes',
    'insights_for_students': 'Yes',
    'practical_tips_for_godly_habits': 'Yes',
    'tabletalk_devotions_with_rc_sproul': 'Yes',
    'erv_living_his_word': 'Yes',
    'experience_the_parables_of_jesus': 'Yes',
    'exploring_biblical_cultures': 'Yes',
    'fearfully_and_wonderfully_made': 'Yes',
    'adventure_bible_family_devotions': 'Yes',
    'boundaries': 'Yes',
    'devotions_for_a_sacred_marriage': 'Yes',
    'family_love_on_which_to_build': 'Yes',
    'night_light_for_couples': 'Yes',
    'night_light_for_parents': 'Yes',
    'niv_devotions_for_couples': 'Yes',
    'streams_in_the_desert_for_kids': 'Yes',
    'nine_key_women_in_the_bible': 'Yes',
    'encouragement_for_today_devotions': 'Yes',
    'girlfriends_in_god_devotional': 'Yes',
    'his_princess_letters': 'Yes',
    'niv_devotions_for_women': 'Yes',
    'wisdom_for_women': 'Yes',
    'women_of_the_bible': 'Yes',
    'biblical_insights_for_men': 'Yes',
    'just_for_dads': 'Yes',
    'men_of_the_bible': 'Yes',
    'niv_devotions_for_men': 'Yes',
    'no_rock_like_our_god': 'Yes',
    'best_is_yet_to_be': 'Yes',
    'encouraging_word_from_max_lucado': 'Yes',
    'coram_deo_daily_meditations_on_gods_presence': 'Yes',
    'hope_in_the_mourning': 'Yes',
    'lifeconnect_devotionals_to_strengthen_your_spiritual_life': 'Yes',
    'praying_your_way_to_spiritual_empowerment': 'Yes',
    'leadership_insight_from_the_maxwell_bible': 'Yes',
    'developing_your_personal_leadership_skills': 'Yes',
    'ministry_advantage': 'Yes',
    'tozer_on_christian_leadership': 'Yes',
    'visual_verse_of_the_day_rvr': 'Yes',
    'evangelio_viviente': 'Yes',
    'un_dia_a_la_vez': 'Yes',
    'salt_and_light': 'Yes',
    "Email": "",
    'Email Type': 'HTML'
}

data2 = {
    "contactlist": [
        "8dd3e567-62dc-4aca-bc0c-9650de13aad4",
        "edac06c6-aa98-4904-98db-400d1d5fae99",
        "81e98b4e-4158-4760-9031-9c2d9e50b666",
        "edfcc3c0-c337-4498-91e0-5d17690185a1",
        "a53cc146-456f-4b57-b0dd-d10956a79963"
    ],
    "email": ""
}

data3 = {
    "contactlist": [
        "6eae0025-3b2f-4532-9b01-dbf89c8abdc9",
        "cf9f67c8-fd15-4d81-811b-2c496eaa8609",
        "29dc5440-a3dc-4292-aede-ed8220afc33c",
        "cf5dc483-2ffc-4a56-afeb-1b2706b226da",
        "c94672ed-9015-431a-822b-af0fb48e8d3d",
        "a398f1f9-68bc-46ab-8bce-cdf54287eb10",
        "bc201ada-55b4-4c3a-8b7d-72f50349c866",
        "b052bdcb-6f18-4b06-a709-061b3b8447db",
        "bff5d5a8-1c83-465a-b5e6-89f9beef25a2",
        "03950982-5f51-4ef9-b582-ea1ecbbcfa99",
        "f924c18b-7f34-4fe0-96fc-569bd0eaa82e",
        "35f77fd9-75fc-4a84-8f05-64a719b4d8a0",
        "64288cb8-2b48-47f1-b8a3-30e8c5e6225c",
        "b38bd67f-17af-4bb3-9ee1-ccaa247c4706",
        "b8ae2438-c8db-4c67-af9e-8f45026e66fd",
        "59df4643-c875-4a6b-870e-b481cf1524a6",
        "50aec8bc-2b47-4c37-ad63-b8412575f286",
        "40331008-1127-4de8-98a8-8f91bf6b84d2",
        "d6e6ecc5-a8a2-4039-8e7f-233fed8b55ac",
        "22614fe8-4180-4223-86e3-089a423acb61",
        "2e8819ad-670c-445d-8e78-ef03baa9b995"
    ],
    "email": ""
}

data4 = {
    "attributes": {},
    "email": "",
    "identifiers": {
    "K1": "otherhealthsystems",
    "categories": "",
    "correlationId": "8d8caf89-2f43-498f-b31d-a46354e40227",
    "source": "Newsletter Listing",
    "tags": "",
    },
    "lists": [
    "Nutrition",
    "Wellness Wire",
    "Women's Wellness",
    "Men's Health",
    "Daily News",
    "Coronavirus Alerts",
    "Senior Health",
    "ADHD",
    "Sleep Challenge",
    "Gut Check Challenge",
    "Loneliness Challenge",
    "Medicare Series - Find the Right Plan",
    "Move Your Body Challenge",
    "AFib",
    "Allergies",
    "Anxiety",
    "Bipolar",
    "COPD",
    "Depression",
    "Diabetes Type 2",
    "Endometriosis",
    "Fibromyalgia",
    "Heart Health",
    "Multiple Sclerosis",
    "IBD",
    "Menopause",
    "Osteoarthritis",
    "Psoriasis",
    "Rheumatoid Arthritis",
    "Migraine",
    ],
    "path": "/homepage",
    "recaptcha": "03AGdBq25UM0eN748IYtQ1GWQFKNystA1b6qHmLlXpZfFiN0JeRxESRbo4OV7FnNTOiupGgs4KlvBTWPJaUZVgQMuQvOY1_VmnOboSHDVcK2GiMXTqbxahqVn11-35Gy8BNyZ87GY3Qod2LtgQJ4m_q3kQk1yiErbxlyc8SCPvSsI5--I7evMLBtEauueNsShBXSWSIoayGwE4UUpExgSkdpo9yGpJo3Nu7UzS8H50Gh-toBmbelwQjaN_uf7Dho5v8Zxo3sKJZfsxr7hjIhmP7WNFdB3tGoYQr6jo_UOrIrRmVk3HHZhV-LtXkQbAlRqAVk7WK9nIQGTrDm6pDRtirvfmVmDq4kI1RXtFF0U-ciCqjz2tHEqJn-bPun7pERSM_loTe_3bHxWQiPWCJTkzKWT0uQ3YEAw_cXqmsx13ik07jVATv8BbtoEe51YJGswU_nmjlz3CgWPT",
    "site": "hl"
}

data5 = {
    "email": "",
    "site": "kprc",
    "subscribes": {
        "acquisition_method": "sailthru_subscription_page",
        "acquisition_time": "1628943081",
        "kprc_0700cst": "1",
        "kprc_1200cst": "1",
        "kprc_2000cst": "1",
        "kprc_askamy": "1",
        "kprc_astros": "1",
        "kprc_breaking": "1",
        "kprc_contests": "1",
        "kprc_corona": "1",
        "kprc_crime": "1",
        "kprc_education": "1",
        "kprc_elections": "1",
        "kprc_entertainment": "1",
        "kprc_frank": "1",
        "kprc_health": "1",
        "kprc_houstonlife": "1",
        "kprc_houstonsportsdaily": "1",
        "kprc_investigates": "1",
        "kprc_olympics": "1",
        "kprc_realestate": "1",
        "kprc_rodeo": "1",
        "kprc_somethinggood": "1",
        "kprc_space": "1",
        "kprc_supportlocal": "1",
        "kprc_texans": "1",
        "kprc_thingstodo": "1",
        "kprc_traffic": "1",
        "kprc_weatherDaily": "1",
        "kprc_wine": "1",
        "stVar": "null",
        "subscription_count": "0",
        "subscriptionformvisit_time": "1628943081"
    }
}

data6 = {
    "email": "",
    "sub": "e879,e883,e884,e241,e882,e881,e889"
}